WebSite/WebSite/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.IO;

using JamZoo.Project.WebSite.Library.Azure;

using JamZoo.Project.WebSite.Models;
using JamZoo.Project.WebSite.Service;
using JamZoo.Project.WebSite.ViewModels;
using JamZoo.Project.WebSite.Enums;
using JamZoo.Project.WebSite.Library.Principal;
using JamZoo.Project.WebSite.Library.DocConvert;

namespace JamZoo.Project.WebSite.Controllers
{
    public class DocumentController : BaseController
    {
        PageImageService pageImgSer = new PageImageService();
        BookcaseService bookSer = new BookcaseService();
        DocumentTypeService docTypeSer = new DocumentTypeService();
        DocumentService Service = new DocumentService();
        CategoryItemService cateItemSer = new CategoryItemService();
        DocumentConvertService docConvSer = new DocumentConvertService();

        public DocumentController()
        {
            
        }
        
        #region CRUD       
        [Authorize]
        public ActionResult List(DocumentListModel criteria, Guid? foldId, string ErrMsg)
        {
            try
            {
                BookcaseModel bookcaseMod = new BookcaseModel();

                if (this.ControllerContext.HttpContext.Request.Cookies.AllKeys.Contains("bookcaseMod"))
                {
                    System.Web.Script.Serialization.JavaScriptSerializer serializer = new System.Web.Script.Serialization.JavaScriptSerializer();
                    HttpCookie bookCookie = Request.Cookies.Get("bookcaseMod");
                    bookcaseMod = serializer.Deserialize<BookcaseModel>(bookCookie.Value.ToString());
                }

                DocumentListModel model = Service.GetList(UserManager.User.Domain, criteria, bookcaseMod.Id, foldId, false);

                if(!string.IsNullOrEmpty(ErrMsg))
                    ModelState.AddModelError("message", ErrMsg);

                return View(model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("message", ex.Message);
            }

            return View(criteria);
        }

        public ActionResult CtrlList(Guid bookCaseId)
        {
            DocumentListModel criteria = new DocumentListModel();
            try
            {
                BookcaseModel bookcaseMod = new BookcaseModel();

                DocumentListModel model = Service.GetList(UserManager.User.Domain, criteria, bookCaseId, out bookcaseMod);

                System.Web.Script.Serialization.JavaScriptSerializer serializer = new System.Web.Script.Serialization.JavaScriptSerializer();
                bookcaseMod.Name = HttpUtility.UrlEncode(bookcaseMod.Name).Replace("+", "%20");
                string jsonbookcaseModel = serializer.Serialize(bookcaseMod);

                this.ControllerContext.HttpContext.Response.Cookies.Remove("bookcaseMod");
                HttpCookie cookie = new HttpCookie("bookcaseMod", jsonbookcaseModel);
                this.ControllerContext.HttpContext.Response.Cookies.Add(cookie);

                return View("List", criteria);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("message", ex.Message);
            }

            return View("List", criteria);
        }

        public ActionResult ApproveList(DocumentListModel criteria)
        {
            try
            {
                DocumentListModel model = Service.GetList(UserManager.User.Domain, criteria, null, null, true);

                return View(model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("message", ex.Message);
            }

            return View(criteria);
        }

        [Authorize]
        public ActionResult Add(int page = 1)
        {
            BookcaseModel bookcaseMod = new BookcaseModel();            

            if (this.ControllerContext.HttpContext.Request.Cookies.AllKeys.Contains("bookcaseMod"))
            {
                System.Web.Script.Serialization.JavaScriptSerializer serializer = new System.Web.Script.Serialization.JavaScriptSerializer();
                HttpCookie bookCookie = Request.Cookies.Get("bookcaseMod");
                bookcaseMod = serializer.Deserialize<BookcaseModel>(bookCookie.Value.ToString());                
            }  

            DocumentModel entity = Service.NewInstance();
            entity.BookcaseId = bookcaseMod.Id;
            entity.DocumentTypeSelectList = docTypeSer.GetList(UserManager.User.Domain, new Guid());

            if (bookcaseMod.CategoryId1 != null)
                entity.CategorItemSelectList1 = cateItemSer.GetList(new Guid(bookcaseMod.CategoryId1.ToString()), "");

            if (bookcaseMod.CategoryId2 != null)
                entity.CategorItemSelectList2 = cateItemSer.GetList(new Guid(bookcaseMod.CategoryId2.ToString()), "");

            if (bookcaseMod.CategoryId3 != null)
                entity.CategorItemSelectList3 = cateItemSer.GetList(new Guid(bookcaseMod.CategoryId3.ToString()), "");
           
            entity.page = page;
            entity.Mode = EditPageMode.Create;
            return View(entity);
        }
        
        [Authorize]
        [HttpPost]
        public ActionResult Create(DocumentModel model, HttpPostedFileBase file, HttpPostedFileBase Coverfile, Guid? foldId)
        {
            BookcaseModel bookcaseMod = new BookcaseModel();
            DocumentTypeModel docTypeMod = new DocumentTypeModel();
            DocumentConvertModel docConvMod = new DocumentConvertModel();

            bookcaseMod = bookSer.Get(model.BookcaseId);


            model.CreateAccountId = UserManager.User.Id;
            model.Domain = UserManager.User.Domain;

            if (ModelState.IsValid)
            {
                try
                {
                    string ErrMsgs = string.Empty;

                    string webFilePath = System.Web.Hosting.HostingEnvironment.MapPath("~/DocConvertFolder");

                    BlobHandler bh = new BlobHandler(UserManager.User.Domain.ToLower());

                    FileInfo fi = new FileInfo(file.FileName);

                    string FileName = string.Format("{0}{1}", model.DocVerMod.Id.ToString(), fi.Extension);

                    if(bookcaseMod.IsVersionControlEnabled)
                    {
                        model.DocVerMod.Version = new decimal(0.1);
                        model.DocVerMod.State = DocVerState.CheckOut;
                        model.DocVerMod.DisplayVersion = "無";
                    }                        
                    else
                    {
                        model.DocVerMod.Version = 1;
                        model.DocVerMod.State = DocVerState.Release;
                        model.DocVerMod.DisplayVersion = "1";
                    }                        
                    
                    
                    model.DocVerMod.ModifyTime = DateTime.Now;
                    model.DocVerMod.ModifyAccountId = UserManager.User.Id;

                    #region 處理圖片
                    if (Coverfile != null)
                    {
                        FileInfo cfi = new FileInfo(Coverfile.FileName);

                        string cFileName = string.Format("{0}{1}", Guid.NewGuid(), cfi.Extension);

                        bh.Upload(Coverfile, cFileName);

                        model.DocVerMod.CoverThumbnailUrl = string.Format("{0}{1}/{2}", WLBlob, UserManager.User.Domain.ToLower(), cFileName);
                    }
                    #endregion

                    #region 處理文件

                    if (file != null)
                    {
                        docTypeMod = docTypeSer.Get(model.DocumentTypeId);

                        if (!docTypeMod.SubFileName.Replace(".", "").Trim().ToLower().Contains(fi.Extension.Replace(".", "")))
                            throw new Exception("檔案格式不符");

                        model.DocVerMod.FileUploadTime = DateTime.Now;

                        model.DocVerMod.FileName = fi.Name;

                        model.DocVerMod.FileSize = file.ContentLength;

                        string SavePath = string.Format("{0}/{1}", webFilePath, FileName);
                        string FileTempFolder = string.Format("{0}/{1}", webFilePath, model.DocVerMod.Id);
                        file.SaveAs(SavePath);

                        bh.Upload(file, FileName);

                        model.DocVerMod.FileUrl = string.Format("{0}{1}/{2}", WLBlob, UserManager.User.Domain.ToLower(), FileName);

                        
                        #region 寫入排程轉檔
                        if (docTypeMod.SubFileName.Replace(".", "").Trim().ToLower() != "mp4" && docTypeMod.SubFileName.Replace(".", "").Trim().ToLower() != "jpg")
                        {
                            docConvMod.Id = Guid.NewGuid();
                            docConvMod.VersionId = model.DocVerMod.Id;
                            docConvMod.ConvertStatus = 0;
                            docConvMod.CreateTime = DateTime.Now;
                            docConvMod.ModifyTime = DateTime.Now;
                            docConvSer.Create(docConvMod, out ErrMsgs);
                            if (!string.IsNullOrEmpty(ErrMsgs))
                                throw new Exception(ErrMsgs);
                        }
                        #endregion

                        fi = new FileInfo(SavePath);
                        fi.Delete();


                    }
                    else
                        throw new Exception("請選擇上傳文件");

                    #endregion


                    if (Service.Create(model, foldId, out ErrMsgs))
                    {
                        return RedirectToAction("List", new { page = model.page, foldId = foldId });
                    }

                    ModelState.AddModelError("message", ErrMsgs);

WebSite/WebSite/Views/Bookcase/Add.cshtml
@using JamZoo.Project.WebSite.Enums;
@using JamZoo.Project.WebSite.Library;
@using System.Web.Script.Serialization;
@model JamZoo.Project.WebSite.Models.BookcaseModel
@{
    if (Model.Name == null)
    {
        Layout = "~/Views/Shared/_Layout_Com.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }    
    string CurrentController = string.Empty;
    if (ViewContext.RouteData.Values["Controller"] != null)
    {
        CurrentController = ViewContext.RouteData.Values["Controller"].ToString();
    }
}
<script type="text/javascript">


</script>
@Html.ActionLink("回上頁", "CtrlList", "Document", new { bookCaseId = Model.Id }, new { @class = "pure-button" })
<p>
    @Html.ValidationMessage("message")
</p>
@using (Html.BeginForm(Model.Mode == EditPageMode.Create ? "create" : "update",
    CurrentController, new { page = Model.page }, FormMethod.Post,
    new { enctype = "multipart/form-data", @class = "pure-form pure-form-aligned" }))
{
    @Html.HiddenFor(p => p.Id)
    @Html.HiddenFor(p => p.ThumbnailUrl)
    @Html.HiddenFor(p => p.Domain)
    @Html.HiddenFor(p => p.CreateAccountId)
    @Html.HiddenFor(p => p.CreateTime)
    
     <div>
        <fieldset style="background-color: white; padding: 30px;">
            <div class="pure-control-group">
                @Html.LabelFor(p => p.Name)
                @Html.TextBoxFor(p => p.Name)
                @Html.ValidationMessageFor(p => p.Name)
            </div>
      
            <div class="pure-control-group">
                @Html.Label("書櫃縮圖")
                <label for="">
                    <input type="file" name="file" id="file" style="width: 800px;" />
                    @if (Model.ThumbnailUrl != null && Model.ThumbnailUrl != "")
                    {
                        <img src=@Model.ThumbnailUrl alt="Mountain View" style="width:304px;height:228px;">
                    }
                </label>
            </div>

            <div class="pure-control-group">
                @Html.LabelFor(p => p.CategoryId1)
                @Html.DropDownListFor(p => p.CategoryId1, Model.CategorSelectList1, new { @class = "pure-input-small" })
            </div>

            <div class="pure-control-group">
                @Html.LabelFor(p => p.CategoryId2)
                @Html.DropDownListFor(p => p.CategoryId2, Model.CategorSelectList2, new { @class = "pure-input-small" })
            </div>

            <div class="pure-control-group">
                @Html.LabelFor(p => p.CategoryId3)
                @Html.DropDownListFor(p => p.CategoryId3, Model.CategorSelectList3, new { @class = "pure-input-small" })
            </div>        

            <div class="pure-control-group">
                @Html.LabelFor(p => p.IsApproveEnabled)
                <label for="Status" class="pure-radio">
                    @Html.RadioButtonFor(p => p.IsApproveEnabled, true) 是&nbsp;
                    @Html.RadioButtonFor(p => p.IsApproveEnabled, false) 否&nbsp;
                </label>
                @Html.ValidationMessageFor(p => p.IsApproveEnabled)
            </div>

            <div class="pure-control-group">
                @Html.LabelFor(p => p.IsVersionControlEnabled)
                <label for="Status" class="pure-radio">
                    @Html.RadioButtonFor(p => p.IsVersionControlEnabled, true) 是&nbsp;
                    @Html.RadioButtonFor(p => p.IsVersionControlEnabled, false) 否&nbsp;
                </label>
                @Html.ValidationMessageFor(p => p.IsVersionControlEnabled)
            </div>

            <div class="pure-control-group">
                @Html.LabelFor(p => p.IsDocumentExpireDelete)
                <label for="Status" class="pure-radio">
                    @Html.RadioButtonFor(p => p.IsDocumentExpireDelete, true) 是&nbsp;
                    @Html.RadioButtonFor(p => p.IsDocumentExpireDelete, false) 否&nbsp;
                </label>
                @Html.ValidationMessageFor(p => p.IsDocumentExpireDelete)
            </div>

            <div class="pure-control-group">
                @Html.LabelFor(p => p.NoInherit)
                <label for="Status" class="pure-radio">
                    @Html.RadioButtonFor(p => p.NoInherit, true) 是&nbsp;
                    @Html.RadioButtonFor(p => p.NoInherit, false) 否&nbsp;
                </label>
                @Html.ValidationMessageFor(p => p.NoInherit)
            </div>

            <div class="pure-control-group">
                <label></label>
                @if (Model.Mode == EditPageMode.Create)
                {
                    <input type="submit" value="新 增" class="pure-button"/>
                }
                else if (Model.Mode == EditPageMode.Update)
                {
                    <input type="submit" value="修 改" class="pure-button" onclick="return Check()" />
                }

            </div>
        </fieldset>
    </div>
}

WebSite/WebSite/Views/Bookcase/List.cshtml
@model JamZoo.Project.WebSite.Models.BookcaseListModel
@{
    Layout = "~/Views/Shared/_Layout_Com.cshtml";
    string CurrentController = string.Empty;
    if (ViewContext.RouteData.Values["Controller"] != null)
    {
        CurrentController = ViewContext.RouteData.Values["Controller"].ToString();
    }
}
<style type="text/css">
    .app-icon {
        margin-top: 10px;
    }

    .field-validation-error {
        color: rgba(284,241,56,1);
    }

    ul.pagination li.active {
        background-color: #4E88C3;
    }

        ul.pagination li.active a {
            background-color: #4E88C3;
            color: white;
        }

    .status {
        width: 50% !important;
    }

    .second-nav {
        width: 50% !important;
    }

    ul.score li label {
        font-size: 24px;
    }

    ul.score li.second {
        color: green;
    }

        ul.score li.second label {
            background: green;
        }

    ul.score li.third {
        color: red;
    }

        ul.score li.third label {
            background: red;
        }

    .slide-in {
        width: 200px;
        left: -163px;
    }

        .slide-in ul li {
            font-size: 24px;
        }

    .result-area table tr th {
        background: #5dc7dd;
        border-bottom: 2px solid #f2ff64;
    }

    .result-area button, .bottom-area button {
        background: #22adca;
        border-bottom: 2px solid #f2ff64;
    }

    ul.pagination li.active a {
        background-color: #22adca;
    }

    .result-area table tr th {
        text-align: left;
    }

    .top-bar {
        background-color: #304D5E;
        border-bottom: 10px solid #0198FF;
    }

    .second-bar {
        background-color: #5dc7dd;
    }

    .second-nav ul li {
        background: #FFFFFF;
    }

    .app-card-bottom {
        border-bottom: 2px solid #0198FF;
        background-color: #5dc7dd;
    }
</style>

<h2>書櫃</h2>
<div>
    <div style="background-color: white; padding: 30px;">
        @Html.Partial("_ErrorMsg", ViewContext.ViewData)
        <p></p>
        @using (Html.BeginForm("List", CurrentController, FormMethod.Get, new { @class = "pure-form" }))
        {
            <div class="pure-u-1-1" style="text-align:right">
                @Html.TextBoxFor(p => p.Search, new { placeholder = "請輸入書櫃名稱" })
                <input type="submit" class="pure-button" value="查詢" />
            </div>
        }
        <p></p>
        @Html.ActionLink("新增", "add", new { page = Model.Page }, new { @class = "pure-button" })
        <p></p>
        <div class="result-area">
            <ul class="app-list">
                @foreach (var Row in Model.Data)
                {
                    <li class="app-card">
                        <a href="~/Document/CtrlList?bookCaseId=@Row.Id">
                            <div class="left">
                                <div class="app-icon">
                                    <img src=@Row.ThumbnailUrl class="APPIcon" width="100" height="100" />
                                </div>
                                <p>@Row.Name</p>
                            </div>
                            <div class="right" style="position:relative">
                                <ul>
                                    <li>狀態：開發產品</li>
                                    <li>自訂分類1：@Row.CategoryName1</li>
                                    <li>自訂分類2：@Row.CategoryName2</li>
                                    <li>自訂分類3：@Row.CategoryName3</li>
                                </ul>
                            </div>

                        </a>
                    </li>
                }
            </ul>
        </div>         
</div>
</div>
<p></p>
@{
    Request.RequestContext.RouteData.Values.Add("Search", Model.Search);
    @Html.Partial("_Pager", (JamZoo.Project.WebSite.Models.PagerModel)Model)
}